# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='assignments',
            field=models.ManyToManyField(to='api.Assignment'),
        ),
    ]
