# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170626_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='assignments',
            field=models.ManyToManyField(blank=True, null=True, to='api.Assignment'),
        ),
    ]
