# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170627_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='assignments',
            field=models.ManyToManyField(blank=True, null=True, related_name='course_of_assignment', to='api.Assignment'),
        ),
    ]
